[package]
name = "crayon-ctrl"
version = "0.1.0"
authors = ["Carlos Valiente <carlo@pepelabs.net>"]
edition = "2018"

[dependencies]
tokio = { "version" = "0.2.11", features = ["full"] }
warp = { "version" = "0.2.1" }
